context7_api_key: ENC[AES256_GCM,data:obbpbf2zTECmLO8+JDWDmJBwO6aSkNiLuDm3oAoKzcgWSu6YNOPz5JJljg==,iv:Z/jBhaI2pJV9tUnR/fjqYdDx1M8zfPdePRXT1W6ksy4=,tag:vgRR8Dv/SQWLFI4VZPjGaw==,type:str]
zai_api_key: ENC[AES256_GCM,data:FZShyYKiKHsJ646ODmkcZt8qygm1AGr7xtZxOCyjptAowN5dRKoctYyfF5njpGfU7Q==,iv:HZD+1RFzMbsdF32x9mYdwi+Cf+7mfVQNxLRCS54iEfs=,tag:5Fkln076B5QfmvHzHDJUbQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFNG1oNmVtQ2toenhOVDVJ
            d0M2bENGODk2NDR1bm5wU0RxWWs3YjhWTlZzCk9MOHpER0xDTDNEVENyUDN5QjN0
            UGJOZ2MxaDZHQ3ZCamkxZGlySm5yNnMKLS0tIGhGTVl3UFJJVE5QOU01a25aSk8w
            YzJKZVJzRTkwTkFYNmdtZzcvQW1jdkkK9eF0V8Rk6UX9G0ARS/YNCTNZJC0TTouc
            3uv+tmKSe6czIbFa2G6YUfAThgd5AyJCz8UVEhRvBn2pqSb4wmfdAQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zqelkaws6jzzv35jq53dz2qpefu0n60p3s3x7lx5yp8lvntx8cjqz7p0sl
    lastmodified: "2026-06-09T12:54:58Z"
    mac: ENC[AES256_GCM,data:gMRfc64+eurkk55r/1DG65Bdq561LUxfcuzNO77ehUodzOB5+ugBvq21K5sBq21zb4QWpahpwSocOxTFGhXveECixbEduyAFhIV2IcMXeHF/crITl1pntx/ZbMefh5WozWYTG9IHn7Ips6gfbQ04DqSLrPYdj0LLlnLcmILw4jI=,iv:S4yoi8HQCXKt2kiCIRes73P9kHKxErPbJjVoaGESyPA=,tag:H3CKvKwRVP+m3Oo2lxajqw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
